# Generated by Django 4.2.3 on 2023-07-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('sage', models.IntegerField()),
                ('sgender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=30)),
                ('semail', models.EmailField(max_length=60)),
                ('sphone', models.IntegerField()),
                ('saddress', models.TextField()),
                ('smothername', models.CharField(max_length=50)),
                ('sfathername', models.CharField(max_length=50)),
                ('simage', models.ImageField(upload_to='student')),
            ],
        ),
    ]
