# Generated by Django 4.2.3 on 2023-07-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_student_sgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sgender',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=40),
        ),
    ]
