# Generated by Django 4.2.3 on 2023-07-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_student_sgender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sfathername',
        ),
        migrations.RemoveField(
            model_name='student',
            name='smothername',
        ),
        migrations.AlterField(
            model_name='student',
            name='sgender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=40),
        ),
    ]
