# Generated by Django 4.2.3 on 2023-07-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_remove_student_sfathername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sphone',
            field=models.CharField(max_length=10),
        ),
    ]
